### ISSUE TITLE
Xcode9.2 issue

### ISSUE THREAD

**Issue by ArthurXu424** [IvanRublev/PersistentStorageSerializable#3]
Hi Ivan,
   I have found an issue on Xcode 9.2, shows as photo below
<img width="1149" alt="screen shot 2017-12-09 at 21 40 33" src="https://user-images.githubusercontent.com/9793711/33796146-e76e3552-dd29-11e7-8dfe-879022f709c2.png">
please help to fix it, thank you.

**Comment by IvanRublev** [comment]
Going to fix this with #2 .
